In [ ]:
!pip install tensorflow 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf

In [ ]:
scalar = tf.constant
scalar

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const')>

In [ ]:
vector=tf.constant([2,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[2,3],[4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
tenser=tf.constant([[[2,3],[4,5],[6,7]]])
tenser

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5],
        [6, 7]]], dtype=int32)>

In [ ]:
tenser.ndim

3

In [ ]:
#creating multiple changeable and unchangeable tensors
changeable_tensor=tf.Variable([3,5])
unchangeable_tensor=tf.constant([4,5])
changeable_tensor,
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>

In [ ]:
changeable_tensor[0].assign(4)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [ ]:
from numpy import random
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>